- src/Views/Shared/AddressSelect.cshtml
- src/Views/Shared/OrganisationSelect.cshtml
- src/Views/Shared/StreetSelect.cshtml
Fix issue on search pages for Address/Org/Street components which caused form to error due to class key already existing within Dictionary.
> fix(DIGITAL-2073): Address/Org/Street search validation

- src/Models/Elements/AddressManual.cs
- src/ViewModels/ErrorViewModel.cs
Error view model within manual address did not use GetCustomErrorId which caused a accessibility issue on validation due to input and error having same id.
> feat(DIGITAL-2365): Changed error view model Id within manual address

- src/Constants/TimeConstants.cs
- src/Mappers/ElementMapper.cs
- src/Models/Elements/TimeInput.cs
- src/Validators/TimeInputValidator.cs
- src/Views/Shared/TimeInput.cshtml
- tests/UnitTests/Mappers/ElementMapperTests.cs
- tests/UnitTests/Validators/TimeInputElementValidatorTests.cs
Moved time suffix to constants file, Updated mapping service/Time Validation to use constant file.
Fixed accessibility issue on TimeInput view due to GetCustomItemId key.
> fix(DIGITAL-2401): Moved time suffix to constant file, Fixed accessability issue within view

- src/Models/Elements/Address.cs
- src/Models/Elements/Element.cs
- src/Models/Elements/Organisation.cs
- src/Models/Elements/Street.cs
- src/Views/Shared/AddressSelect.cshtml
- src/Views/Shared/OrganisationSelect.cshtml
- src/Views/Shared/StreetSelect.cshtml
- Added override to DisplayHint to allow for Select Hint on Address/Street/Organisation.
- adjusted logic for class value based on if model isValid
> feat(2375): Validate DS implementation for Select inputs

- src/Views/Home/Success.cshtml
- src/Views/Shared/Header.cshtml
- Update class for service name within header
- Updated panel body class within success page panel
> chore(header/success): updated class for service name in header and body panel

- src/Models/Elements/DatePicker.cs
- src/Services/PageService/PageService.cs
- Fixed datepicker value disappearing on back
- Fixed bug when navigating back to pageone of form would clear whole form due to formname check not respecting case
> fix(DatePicker): Fixed value disappearing on back

- src/Helpers/ElementHelpers/ElementHelper.cs
- src/Models/Elements/AddressManual.cs
- Address manual now checks previous answers to populate address manual inputs
> fix(addressmanual): address manual populates value on back

- src/ContentFactory/SuccessPageContentFactory.cs
amended the button text. to drop the type.
> fix(): amended download button text for acc and inc

- src/ContentFactory/PageFactory.cs
- src/ViewModels/FormBuilderViewModel.cs
- src/Views/Shared/Header.cshtml
- tests/UnitTests/ContentFactory/PageFactoryTests.cs
- tests/UnitTests/Services/PageServicesTests.cs
- Removed properties from viewmodel not longer required or duplicated
> refactor(ViewModel): Removed unused properties from viewmodel

- MakefileHelp
- Ignore this pullrequest, testing github actions for runnning unit tests
> chore(Project): testing github actions

- .github/dotnet-core.yml
- MakefileHelp
- Added github action to run unit test on pullrequest/push.
> feat(Project): added github action for unit tests

- .github/workflows/dotnet-core.yml
- README.md
Added workflow step to cache nuget packages
> feat(workflow): addec nuget cache

- src/Views/Shared/Map.cshtml
Removed unused class from map view
> chore(map): removed class on map element view

- src/web.config
> fix(webconfig): remove hostingmodel

- src/Startup.cs
Add possible solution to issue with datepicker in Safari using US format since 3.1 upgrade
- [x ] Code compiles correctly
- [n/a ] Created tests for the new changes
- [x ] All tests passing
- [n/a ] Extended the README / documentation, if necessary
> fix(startup): add alternative culture registration

- src/Controllers/HomeController.cs
- src/Startup.cs
- tests/UnitTests/Controllers/HomeControllerTest.cs
Add logging for debugging
- [x ] Code compiles correctly
- [n/a ] Created tests for the new changes
- [x ] All tests passing
- [n/a ] Extended the README / documentation, if necessary
> Safari date issue

- src/Startup.cs
Setup route pattern for controllers, to allow error controller to be resolved, due to having no route attribute defined
> fix(project): Routing

- src/Startup.cs
Removed RequestLocalization and supportedCultures config.
Remove SerializerSettings for newtonsoft.
> chore(startup): removed localization/supported cultures

- src/Models/Properties/ElementProperties/BaseProperty.cs
- src/Views/Shared/AddressManual.cshtml
- src/Views/Shared/AddressSearch.cshtml
- src/Views/Shared/Checkbox.cshtml
- src/Views/Shared/DateInput.cshtml
- src/Views/Shared/DatePicker.cshtml
- src/Views/Shared/FileUpload.cshtml
- src/Views/Shared/InsetText.cshtml
- src/Views/Shared/Radio.cshtml
- src/Views/Shared/Select.cshtml
- src/Views/Shared/StreetSearch.cshtml
- src/Views/Shared/Textarea.cshtml
- src/Views/Shared/Textbox.cshtml
Added ability to allow elements to display an insetText if Properties.IAG is provided.
Updated wiki entries with new property.
**Elements Updated with supported:**
- Date input
- Date picker
- Fileupload
- Radio
- Select
- Textarea
- Textbox
- Timeinput
> feat(DIGITAL-3201): added ability to display inset text on elements

- .github/workflows/dotnet-core.yml
Updated workflow to target 'develop' branch
> chore(workflow): updated branch workflow is ran against

- src/Startup.cs
- src/Utils/ServiceCollectionExtensions/ServiceCollectionExtensions.cs
- src/form-builder.csproj
- tests/form-builder-tests-unit.csproj
Update Gateways package to 5.0.1, move the registration of gateways to ServiceCollectionExtensions
> chore(proj): update Gateways package, register Gateways in the ServiceCollectionExtensions

- src/Views/Shared/TimeInput.cshtml
Added strong label support to timeinput
> chore(time): added stronglabel support

- src/Config/appsettings.local.json
Changed serilog log level on local for system and Microsoft
> chore(config): changed serilog log level for system/microsoft

- src/Config/appsettings.json
- src/Views/Shared/Header.cshtml
Updated polly policies on civicapay and gateway
> fix(config): polly policies change on gateway config

- src/Validators/EmailElementValidator.cs
Amend email regex for schools email
> fix: amend email Regex

- src/Builders/ElementBuilder.cs
- src/Models/Elements/Button.cs
- src/Models/Elements/FileUpload.cs
- src/Models/Properties/ElementProperties/ButtonProperty.cs
- src/Startup.cs
- src/Views/Shared/Button.cshtml
- src/Views/Shared/_Layout.cshtml
- tests/UnitTests/Models/Elements/ButtonTests.cs
Moved onChange event for file input type to data module
Added SMBCFrontend.initAll() within layout
Added ability to disable button on click via property DisableOnClick
> feat(button/fileupload): added ability to disable button on click, moved JS to data-modules

- src/Conditions/ConditionValidator.cs
- src/Conditions/StringComparator.cs
- src/Enum/ECondition.cs
- tests/UnitTests/Conditions/ConditionsTestsWithComparisonValues.cs
> chore(conditions): add IsOneOf condition

- src/Conditions/ConditionValidator.cs
- src/Enum/ECondition.cs
- src/Models/Condition.cs
- tests/UnitTests/Conditions/ConditionsTests.cs
- tests/UnitTests/Conditions/ConditionsTestsWithComparisonValues.cs
Remove Checkbox contains for Contains
> chore(condition): replace checkboxcontains with contains

- src/Config/appsettings.qa.json
> chore(appsettings): add authToken for test analystics

- src/Conditions/ConditionValidator.cs
- src/Conditions/StringComparator.cs
- src/Config/appsettings.local.json
- src/Enum/ECondition.cs
- src/Helpers/PageHelpers/IPageHelper.cs
- src/Helpers/PageHelpers/PageHelper.cs
- src/Models/Condition.cs
- src/Models/FormSchema.cs
- src/Services/RetrieveExternalDataService/RetrieveExternalDataService.cs
- src/Services/SubmitService/SubmitService.cs
- tests/Builders/ConditionBuilder.cs
- tests/UnitTests/Conditions/Any/AnyConditionTests.cs
- tests/UnitTests/Conditions/ConditionsTests.cs
- tests/UnitTests/Helpers/PageHelperTests.cs
Added Any condition type
https://github.com/smbc-digital/form-builder/wiki/Conditions#any-condition
> feat(condition): any condition type

- src/Conditions/ConditionValidator.cs
- src/Conditions/StringComparator.cs
- src/Config/appsettings.local.json
- src/Enum/ECondition.cs
- src/Helpers/PageHelpers/IPageHelper.cs
- src/Helpers/PageHelpers/PageHelper.cs
- src/Models/Condition.cs
- src/Models/FormSchema.cs
- src/Services/RetrieveExternalDataService/RetrieveExternalDataService.cs
- src/Services/SubmitService/SubmitService.cs
- tests/Builders/ConditionBuilder.cs
- tests/UnitTests/Conditions/Any/AnyConditionTests.cs
- tests/UnitTests/Conditions/ConditionsTests.cs
- tests/UnitTests/Helpers/PageHelperTests.cs
> feat(condition): any condition type (#188)

- src/Views/Shared/_Layout.cshtml
Revert main div placement and remove role from div
> fix: revert main and div change, removing role from div

- src/Config/appsettings.local.json
- src/Constants/ValidationConstants.cs
- src/Validators/AddressPostcodeValidator.cs
- src/Validators/ManualAddressValidator.cs
- src/Validators/PostcodeElementValidator.cs
- src/Validators/RequiredElementValidator.cs
- src/Validators/StockportAddressPostcodeElementValidator.cs
- src/Validators/StockportPostcodeElementValidator.cs
- tests/UnitTests/Validators/EmailElementValidatorTests.cs
- tests/UnitTests/Validators/RegexValidatorTests.cs
Updated default required validation to 
- Enter the {label}
Updated empty and invalid postcode validation message to 
- Enter a postcode in the correct format
- Enter the postcode
> chore(validation): updated default validation message

- src/Models/Actions/Action.cs
- src/Services/PageService/PageService.cs
- Remove unused ILogger from PageService.cs
- Add pragma disable in Action.cs for accepted warning
> fix: remove unused ILogger and add pragme disable for accepted warning

- src/Helpers/ElementHelpers/ElementHelper.cs
- src/Models/Elements/Map.cs
- tests/UnitTests/Helpers/ElementHelperTests.cs
Fixed logic issue on generating summary when formSchemaQuestions check was not inverted so was not generating any summary
Add test for GenerateQuestionAndAnswersList method
> fix(sumary): changed check for generating summary

- src/ContentFactory/PageFactory.cs
- src/Properties/launchSettings.json
Add back functionality for Street/Address/Organisation for the first page of the form.
> Back button

- .git-crypt/keys/default/0/0EB878A794E2742DBFC847FA73970E35C77B8DD7.gpg
New collaborators:
C77B8DD7 Harry Woodall <harry.woodall@stockport.gov.uk>
> Add 1 git-crypt collaborator

- src/Models/Elements/Address.cs
- src/Models/Elements/Street.cs
Changed select list text for addresds/street when single result is found.
> chore: changed select list text for when single results

- src/Views/Shared/CookieBanner.cshtml
Set the link text for the cookie notice to an accessible phrase.
> fix(): cookie banner improved for accessibility

- src/Extensions/ListExtension.cs
- src/Validators/RestrictMimeTypeValidator.cs
- src/Views/Shared/MultipleFileUpload.cshtml
- tests/UnitTests/Validators/RestrictMimeTypeValidatorTest.cs
Updated validation message for mime types
> chore(fileupload): changed validation message for mime types

- src/Validators/RestrictFileSizeValidator.cs
- src/Views/Shared/MultipleFileUpload.cshtml
- tests/UnitTests/Validators/RestrictFileSizeValidatorTests.cs
Changed File uploaded heading to h3
Updated file size validator text to include missing 'be'
Removed space before x MB text on file size validator
> chore(fileupload): heading/validator changes

- src/Views/Shared/ErrorBase.cshtml
Changed errorbase class to smbc-error-message
> chore(errorbase): changed errror-message class to smbc-error-message

- src/robots.txt
> chore(app): added robots.txt file

- src/Mappers/ElementMapper.cs
> chore(element-mapper): change declaration return values

- src/Views/Shared/MultipleFileUpload.cshtml
Adding padding-left for file input when error container shows up
> Chore: Add padding-left:5px for file input when error occurs

- src/Models/Elements/MultipleFileUpload.cs
- src/Models/Properties/ElementProperties/BaseProperty.cs
- src/Services/PageService/PageService.cs
- src/Validators/MultipleFileUploadElementValidator.cs
- src/Views/Shared/LabelH1.cshtml
- src/Views/Shared/LegendH1.cshtml
- src/Views/Shared/MultipleFileUpload.cshtml
- tests/UnitTests/Services/PageServicesTests.cs
- tests/UnitTests/Validators/MultipleFileUploadElementValidatorTests.cs
Added logic to support optional file upload element
> feat: optional file upload

- src/Constants/SystemConstants.cs
- tests/UnitTests/Validators/RestrictFileSizeValidatorTests.cs
Changed default max file size to 10Mb
> chore(Constants): change default max file size to 10Mb

- src/Config/appsettings.json
- src/Mappers/ElementMapper.cs
- src/Validators/MultipleFileUploadElementValidator.cs
- src/Validators/RestrictCombinedFileSizeValidator.cs
- tests/UnitTests/Validators/MultipleFileUploadElementValidatorTests.cs
- tests/UnitTests/Validators/RestrictCombinedFileSizeValidatorTests.cs
Updated disallowed keys config for Submit key
Changed linq in validators to find element questionId not firstOrDefault
> fix(fileupload): updated validator and disallowed keys config

- src/Constants/ValidationConstants.cs
- src/Validators/MultipleFileUploadElementValidator.cs
- tests/UnitTests/Validators/MultipleFileUploadElementValidatorTests.cs
> chore: refactor no selected files

- src/Views/Shared/MultipleFileUpload.cshtml
Changed h3 to h2 to fix headings order
> fix(fileupload): changed html structure for section heading order

- src/Builders/RouteValueDictionaryBuilder.cs
- src/Controllers/HomeController.cs
- src/Enum/EHttpActionType.cs
- src/Extensions/StringExtensions.cs
- src/Helpers/IncomingDataHelper/IncomingDataHelper.cs
- src/Helpers/PageHelpers/IPageHelper.cs
- src/Helpers/PageHelpers/PageHelper.cs
- src/Models/FormAnswers.cs
- src/Models/IncomingValue.cs
- src/Models/Page.cs
- src/Services/MappingService/MappingService.cs
- src/Services/PageService/Entities/ProcessPageEntity.cs
- src/Services/PageService/IPageService.cs
- src/Services/PageService/PageService.cs
- src/Utils/ServiceCollectionExtensions/ServiceCollectionExtensions.cs
- src/Views/Home/Submit.cshtml
- tests/Builders/IncomingValuesBuilder.cs
- tests/UnitTests/Controllers/HomeControllerTest.cs
- tests/UnitTests/Helpers/PageHelperTests.cs
- tests/UnitTests/Services/FileUploadServiceTests.cs
- tests/UnitTests/Services/IncomingDataHelperTests.cs
- tests/UnitTests/Services/MappingServiceTests.cs
- tests/UnitTests/Services/PageServicesTests.cs
Added support for Incoming Values on Get via QueryStrings. new Property added to specify If incoming values are to be retirved on Get or Post via QueryStrings or PostData and mapped to an appropriate target Mapping value.
> feat: IncomingValues on Get

- src/Views/Shared/DocumentUpload.cshtml
-update button to open in a new window for 'upload your documents'
> chore: update upload your documents button to open a new window

- src/Conditions/ConditionValidator.cs
- src/Conditions/FileUploadComparator.cs
- src/Config/appsettings.json
- src/Enum/ECondition.cs
- src/Models/Elements/DocumentUpload.cs
- src/Models/FormSchema.cs
- src/Properties/launchSettings.json
- src/Services/PageService/PageService.cs
- tests/UnitTests/Cache/CacheTests.cs
- tests/UnitTests/Conditions/ConditionsTestsWithComparisonValues.cs
- tests/UnitTests/Services/PageServicesTests.cs
Amending the page processing to route correctly
Add new FileUploadComparator for use with document-upload success page
> feat(document-upload): add document-upload out of form logic

- src/Extensions/FormAnswersExtensions.cs
update GetReducedAnswers() to handle document upload when sending file
> chore: update GetReducedAnswers()

- tests/unit-tests/UnitTests/Services/FileUploadServiceTests.cs
remove duplicate unit test method
> Chore: remove duplicate unit test method

- src/robots.txt
> chore(app): added robots.txt

- src/Views/Shared/MultipleFileUpload.cshtml
- src/Views/Shared/Recaptcha.cshtml
Moved recaptcha to partial added data-module for smbc-frontend js to append attributes for accessibility
> chore(views): moved recaptcha to partial

- src/Startup.cs
Fix middleware warning log "Failed to determine the https port for redirect."
couple ways to do this could of set it in appsettings.json also went adding it in ConfigureServices
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#port-configuration
> chore(prject): added https redirect 

- src/Startup.cs
Fix middleware warning log "Failed to determine the https port for redirect."
couple ways to do this could of set it in appsettings.json also went adding it in ConfigureServices
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#port-configuration
> chore(prject): added https redirect

- src/Startup.cs
> revert(startup): setup https redirect

- src/Startup.cs
Revert commit for https redirect in startup
> revert https redirect

- tests/unit-tests/UnitTests/Factories/Schema/SchemaFactoryTests.cs
> fix: fix tests for schema provider

- src/Config/appsettings.local.json
- src/Configuration/ITagManagerConfiguration.cs
- src/Configuration/TagManagerConfiguration.cs
- src/Factories/Schema/SchemaFactory.cs
- src/Providers/SchemaProvider/ISchemaProvider.cs
- src/Providers/SchemaProvider/LocalFileSchemaProvider.cs
- src/Providers/SchemaProvider/S3FileSchemaProvider.cs
- src/Startup.cs
- src/Utils/ServiceCollectionExtensions/ServiceCollectionExtensions.cs
- src/Views/Shared/TagManagerBody.cshtml
- src/Views/Shared/TagManagerHead.cshtml
- tests/unit-tests/UnitTests/Factories/Schema/SchemaFactoryTests.cs
Reverts smbc-digital/form-builder#301
> Revert "feat: add check on validateSchemaName that is Redis doesn't contain t…"

- src/Controllers/ErrorController.cs
- src/Controllers/HomeController.cs
- src/Factories/Schema/SchemaFactory.cs
- src/Providers/SchemaProvider/LocalFileSchemaProvider.cs
- src/Services/PageService/PageService.cs
- tests/unit-tests/UnitTests/Services/PageServicesTests.cs
Passing null back from ProcessPage to allow controllers to return a 404 if needed
> fix: pass null back from ProcessPage if can't find form in index

- src/Controllers/ErrorController.cs
- src/Controllers/HomeController.cs
- src/Providers/SchemaProvider/S3FileSchemaProvider.cs
- src/Views/Error/Index.cshtml
- src/Views/Error/NotFound.cshtml
- src/Views/Shared/Header.cshtml
> feat: Add not found action and view

- src/Controllers/ErrorController.cs
- src/Controllers/HomeController.cs
- src/Providers/SchemaProvider/S3FileSchemaProvider.cs
- src/Views/Error/Index.cshtml
- src/Views/Error/NotFound.cshtml
- src/Views/Shared/Header.cshtml
Co-authored-by: Jonathan Hadley <jonathan.hadley@stockport.gov.uk>
Merge develop to master
> feat: Add not found action and view (#307)

- src/Views/Shared/Header.cshtml
Inverting isError check in header
> fix: invert isError default for header check

- src/Models/Elements/Warning.cs
Remove unused using to trigger pipeline
> Pipeline test

- src/Enum/EElementType.cs
- src/Models/Elements/Link.cs
- src/Models/Properties/ElementProperties/LinkProperty.cs
- src/Views/Shared/Link.cshtml
> chore (Link) Add new link element

- src/Controllers/HomeController.cs
- src/ViewModels/SuccessViewModel.cs
- src/Views/Home/Success.cshtml
Fixed feedback link not appearing on Success pages due to missing ViewData value.
> fix(Success): fixed success view not containg feedbackUrl

- src/Extensions/StringExtensions.cs
- src/Models/Elements/Booking.cs
- tests/unit-tests/UnitTests/Extensions/StringExtensionsTests.cs
Added env check for next month post request url within calendar.
> fix(booking): added env check for url when not local

- src/Models/Elements/Booking.cs
- src/Views/Shared/Booking/Booking.cshtml
- tests/unit-tests/UnitTests/Models/Elements/BookingTests.cs
move the logic to determine the inset text to the element rather than the view
update existing unit tests to check logic
> chore(Booking): move logic from view to element, update unit tests

- src/Models/Page.cs
- tests/unit-tests/UnitTests/Models/PageTests.cs
Added pagelsug to improve exception message on GetNextPage method
> chore(Model): Updated exception message to include page slug

- src/Models/Page.cs
- tests/unit-tests/UnitTests/Models/PageTests.cs
Added pagelsug to improve exception message on GetNextPage method
> fix(Model): Updated exception message for GetNextPage

- src/Builders/ElementBuilder.cs
- src/Extensions/BookingResources.cs
- src/Extensions/ElementExtentions.cs
- src/Helpers/PageHelpers/PageHelper.cs
- src/Models/Properties/ElementProperties/BookingProperty.cs
- src/Services/BookingService/BookingService.cs
- src/Services/MappingService/MappingService.cs
- tests/unit-tests/UnitTests/Extensions/BookingResourceExtensionsTests.cs
- tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs
- tests/unit-tests/UnitTests/Services/BookingServiceTests.cs
Added support for Optional Resources to booking element.
Updated wiki with optional resources infomation:
https://github.com/smbc-digital/form-builder/wiki/Booking
> feat(Booking): Support for optional booking resources

- src/Services/BookingService/BookingService.cs
- src/Services/MappingService/MappingService.cs
- src/form-builder.csproj
- tests/unit-tests/UnitTests/Services/BookingServiceTests.cs
- tests/unit-tests/form-builder-tests-unit.csproj
Handle empty string response from BookingService to process as Customer Address
Add MapAddress to set location as Customer Address
Update unit tests
> chore(Booking location): handle CustomerAddress as location, update tests

- src/Extensions/AddressExtensions.cs
- src/Services/BookingService/BookingService.cs
- src/form-builder.csproj
- tests/unit-tests/UnitTests/Extensions/AddressExtensionsTests.cs
- tests/unit-tests/form-builder-tests-unit.csproj
> chore(location) titlecase for string

- src/Services/BookingService/BookingService.cs
Resolved submit issue if user goes back but don't change appointment date
> chore:(location) fix for back button then submit issue

- src/Constants/BookingConstants.cs
- src/Extensions/DictionaryExtensions.cs
- src/Models/Time/TimePeriod.cs
- src/Views/Shared/Time/Time.cshtml
- src/Views/Shared/Time/TimePeriodNoJs.cshtml
Added noscript section to Time to handle time period selection differently in the case a user does not have javascript enabled.
> fix(time): added nojs option for time selection

- src/Extensions/DictionaryExtensions.cs
> fix(time): Seperate value retrieval

- src/Models/Time/TimePeriod.cs
- src/Utils/Extensions/DateTimeExtensions.cs
- src/Views/Shared/Time/TimePeriod.cshtml
- src/Views/Shared/Time/TimePeriodNoJs.cshtml
- tests/unit-tests/UnitTests/Extensions/DateTimeExtensionsTests.cs
Added aria describedby values to time period values to improve screen reader experience when navigating the radio inputs.
> fix(time): added aria-describedby to inputs

- src/Builders/ElementBuilder.cs
- src/Models/Elements/Booking.cs
- src/Models/Properties/ElementProperties/BookingProperty.cs
- src/Models/Time/TimePeriod.cs
- src/Views/Shared/Time/TimePeriod.cshtml
- src/Views/Shared/Time/TimePeriodNoAppointments.cshtml
- src/Views/Shared/Time/TimePeriodNoJs.cshtml
- tests/unit-tests/UnitTests/Models/Elements/BookingTests.cs
> Am pm message text

- src/Startup.cs
> revert: added https redirect

- src/Services/AddressService/AddressService.cs
- src/Services/StreetService/StreetService.cs
- tests/unit-tests/UnitTests/Services/AddressServiceTests.cs
- tests/unit-tests/UnitTests/Services/StreetServiceTests.cs
Updated ApplicationException message to include provider and searchterm
> chore(service): updated exception message within Street/Address service

- src/Models/Properties/ElementProperties/BookingProperty.cs
> chore(AmPm) appointment to appointments text changed

- src/Factories/Transform/Lookups/LookupSchemaTransformFactory.cs
- src/Factories/Transform/ReusableElements/ReusableElementSchemaTransformFactory.cs
- src/Gateways/S3Gateway.cs
- src/Helpers/DocumentCreation/DocumentCreationHelper.cs
- src/Helpers/Session/SessionHelper.cs
- src/Mappers/ElementMapper.cs
- src/Middleware/HeaderConfiguration.cs
- src/Providers/Address/CRMAddressProvider.cs
- src/Providers/Booking/BookingProvider.cs
- src/Providers/EmailProvider/AwsSesProvider.cs
- src/Providers/Organisation/CRMOrganisationProvider.cs
- src/Providers/Organisation/ServiceOrganisationProvider.cs
- src/Providers/SchemaProvider/LocalFileSchemaProvider.cs
- src/Providers/StorageProvider/DistributedCacheWrapper.cs
- src/Providers/Street/CRMStreetProvider.cs
- src/Providers/Street/ServiceStreetProvider.cs
Style changes only... you can launch your solution to double check, but this requires a visual check also.
Visually scan through changes in files and see if it is kind on the eyes.
Please feedback or discuss if not...
> Changed to Expression Body definitions

- src/Models/Elements/Booking.cs
Adding JsonIgnore attributes to booking element
> fix: add JsonIgnore attributes to booking element

- src/Views/Shared/Time/TimePeriodNoAppointments.cshtml
- tests/unit-tests/UnitTests/Models/PageTests.cs
> patch: update text for time period no appointment view

- src/Views/Shared/HtmlElements/Footer/Footer.cshtml
> feat(footer): updated footer copyright data

- src/Models/Elements/DateInput.cs
> patch: Fix for empty dateinput component causing date validation errors

- src/web.config
- [] Extended the README / documentation, if necessary n/a
> patch: Remove X-Powered-By header in web.config

- src/Startup.cs
- [] Extended the README / documentation, if necessary n/a
> patch: add secure cookie flag

- src/Startup.cs
> patch: Add cache control headers - nocache and nostore to startup

- src/Views/Shared/HtmlElements/Headings/H2.cshtml
- src/Views/Shared/HtmlElements/Headings/H3.cshtml
> fix(heading): update switch for heading size

- src/Models/Page.cs
- tests/unit-tests/UnitTests/Models/PageTests.cs
An error appears from time to time about being unable to determine NextPage when processing a form. Added additional debug infomatioin to exception when GetNextPage fails to determine next page
> debug(page): added additional info to exception

- src/Services/MappingService/MappingService.cs
- tests/unit-tests/UnitTests/Services/MappingServiceTests.cs
Added log to submit service to investgate possible theory reduced answers could be returning empty list of answers.
> debug(MappingService): added log to reduced answers

- tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs
- tests/unit-tests/UnitTests/Providers/ReferenceNumberProviders/ReferenceNumberProviderTests.cs
> chore: update tests code

- .github/workflows/dotnet-core.yml
- src/form-builder.csproj
- tests/unit-tests/UnitTests/Services/PayServiceTests.cs
- tests/unit-tests/UnitTests/Services/RetrieveExternalDataServiceTests.cs
- tests/unit-tests/UnitTests/Services/SubmitServiceTests.cs
- tests/unit-tests/form-builder-tests-unit.csproj
Updating FormBuilder and tests to .NET 5
> major: Update Form Builder to .NET 5

- src/Constants/SystemConstants.cs
- src/Extensions/ElementExtentions.cs
- src/Helpers/PageHelpers/PageHelper.cs
- src/Views/Shared/HtmlElements/Inputs/Checkbox/CheckboxOptions.cshtml
- src/Views/Shared/HtmlElements/Inputs/Radio/RadioOptions.cshtml
- tests/unit-tests/UnitTests/Extensions/ElementExtentionsTests.cs
- tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs
Added support for conditional revealing condtent within checkbox. This is the same as what was done on radio.
- Updated Checkbox View to include required data module for revealing content
- Updated Checkbox View to include data-aria-controls on options when conditional element supplied
Updated wiki entry with link to conditionally revealing content
- https://github.com/smbc-digital/form-builder/wiki/Radio
- https://github.com/smbc-digital/form-builder/wiki/Checkbox
> feat(checkbox): Conditionally revealing content

- src/Validators/IntegrityChecks/Behaviours/CurrentEnvironmentSubmitSlugsCheck.cs
- src/Validators/IntegrityChecks/Behaviours/EmptyBehaviourSlugsCheck.cs
- src/Validators/IntegrityChecks/Behaviours/SubmitSlugsHaveAllPropertiesCheck.cs
- src/Validators/IntegrityChecks/Elements/DateValidationsCheck.cs
- src/Validators/IntegrityChecks/Elements/InvalidQuestionCheck.cs
- src/Validators/IntegrityChecks/Elements/InvalidTargetMappingValueCheck.cs
- src/Validators/IntegrityChecks/Form/AnyConditionTypeCheck.cs
- src/Validators/IntegrityChecks/Form/BookingQuestionIdExistsForCustomerAddressCheck.cs
- src/Validators/IntegrityChecks/Form/ConditionalElementCheck.cs
- src/Validators/IntegrityChecks/Form/DynamicLookupChecks.cs
- src/Validators/IntegrityChecks/Form/EmailActionsCheck.cs
- src/Validators/IntegrityChecks/Form/HasDuplicateQuestionIdsCheck.cs
- src/Validators/IntegrityChecks/Form/PaymentConfigurationCheck.cs
- src/Validators/IntegrityChecks/Form/RetrieveExternalActionsCheck.cs
- src/Validators/IntegrityChecks/Form/ValidateActionCheck.cs
- src/Validators/IntegrityChecks/FormSchemaIntegrityValidator.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/BookingElementCheckTests.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/ConditionalElementsAreValidCheckTests.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/DynamicLookupCheckTests.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/PaymemtConfigurationCheckTests.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/RetrieveExternalActionsCheckTests.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/SubmitSlugsHaveAllPropertiesCheckTests.cs
> feat(clean_up_using_statements): reorder

- src/Constants/BookingConstants.cs
- src/Mappers/ElementMapper.cs
- src/Models/Elements/Booking.cs
- src/Services/BookingService/BookingService.cs
- src/Services/SubmitService/SubmitService.cs
- src/form-builder.csproj
- tests/unit-tests/UnitTests/Mappers/ElementMapperTests.cs
- tests/unit-tests/UnitTests/Services/BookingServiceTests.cs
- tests/unit-tests/form-builder-tests-unit.csproj
* hash the BookingId in the BookingService
* map the HashedId in the MappingService
* update unit tests
> feat(Booking): hash the bookingId and map to the submission data

- src/Constants/BookingConstants.cs
- src/Mappers/ElementMapper.cs
- src/Models/Elements/Booking.cs
- src/Providers/Booking/FakeBookingProvider.cs
- src/Services/BookingService/BookingService.cs
- src/Services/SubmitService/SubmitService.cs
- tests/unit-tests/UnitTests/Mappers/ElementMapperTests.cs
- tests/unit-tests/UnitTests/Services/BookingServiceTests.cs
> refactor(Booking): move hashing of booking id to ElementMapper

- src/Validators/IntegrityChecks/Form/HasDuplicateQuestionIdsCheck.cs
add Summary and DocumentUpload elements to the ignored elements for DuplicateQuestionIds
> fix(IntegrityCheck): 

- src/Providers/Booking/FakeBookingProvider.cs
> fix(provide): Updated fake booking provider logic

- src/Helpers/PageHelpers/PageHelper.cs
- src/Models/Properties/ElementProperties/BaseProperty.cs
Add OrderAlphabetically flag to order options
> feat(option) Add asc ordering to radio and checkbox option

- src/Utils/Startup/ServiceCollectionExtensions.cs
Updated GetValue on TagManager Id retrieval
> fix(Startup): fixed tag manager getValue from config

- src/Utils/Startup/ServiceCollectionExtensions.cs
> fix(Startup): fixed tag manager getValue from config (#445)

- src/Utils/Startup/ServiceCollectionExtensions.cs
> hotfix: add redis config extending timeout to 30seconds

- src/Utils/Startup/ServiceCollectionExtensions.cs
Reverts smbc-digital/form-builder#451
> Revert "Merge pull request #447 from smbc-digital/develop"

- src/Utils/Startup/ServiceCollectionExtensions.cs
Change lifetime of cacheWrapper to Transient to align with IDistributedCache
> chore(CacheWrapper): change lifetime of cachewrapper

- src/Services/TemplatedEmailService/TemplatedEmailService.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/Validators/IntegrityChecks/Form/TemplatedEmailActionCheck.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/Form/TemplatedEmailActionCheckTests.cs
Add integrity check for TemplatedEmail
> chore(IntegrityCheck) TemplatedEmail

- src/Utils/Startup/ServiceCollectionExtensions.cs
Update service collection to include redis 'IncludePerformanceCountersInExceptions'
> chore(startup) add performance exception

- src/Extensions/FormAnswersExtensions.cs
- src/Models/Page.cs
Reverts smbc-digital/form-builder#471
> Revert "fix: remove check on answers to finish form reduction, change logic t…"

- src/Validators/MaxLengthvalidator.cs
Exclude checkoutlist from max validator
> fix(validator) exclude checkboxlist from max length validator

- src/Views/Shared/FileUpload/MultipleFileUpload.cshtml
Requested change by UX to move the recapcha below the upload file button
> fear(DIGITAL-4067): moved recaptcha module to below upload button

- src/Views/Payment/Declined.cshtml
> Payment endpoint page

- src/Providers/EnabledFor/TimeWindow.cs
Change TimeWindow comparison to use UTC
> fix(TimeWindow): Updated DateTime comparions to UTC

- src/Startup.cs
> fix(Cookie):  set secure policy to always

- src/Startup.cs
Set anti foergey token to be secure
> chore(Anti): Added secure policy to Anti forgery

- src/Views/Shared/_Layout.cshtml
- src/Views/Shared/_LayoutError.cshtml
Remove media print and reolsve favicon ealier
> chore(Layout): remove media print from favicon

- src/Startup.cs
- src/Views/Shared/_Layout.cshtml
- src/Views/Shared/_LayoutError.cshtml
> Fav icon change

- src/Services/MappingService/MappingService.cs
- src/Startup.cs
- src/form-builder.csproj
- tests/unit-tests/UnitTests/Services/MappingServiceTests.cs
- tests/unit-tests/form-builder-tests-unit.csproj
Added log to provide additional device infomation on when mapping service is returning null or empty list to identify if issue is device related or crawler.
> debug(Mapping): Added package for device information

- src/Factories/Transform/UserSchema/AddAnotherPageTransformFactory.cs
The style for 'Add another'  remove button.
> chore(addanother): Remove button styling

- src/Builders/ElementBuilder.cs
- src/Factories/Transform/UserSchema/AddAnotherPageTransformFactory.cs
- src/Models/Properties/ElementProperties/BaseProperty.cs
- tests/unit-tests/UnitTests/Factories/Transform/AddAnotherPageTransformFactoryTests.cs
Add AppendText property to allow Add Another button content to be appended
> refactor(AddAnother): add property to manage Add another button content

- src/Factories/Transform/UserSchema/AddAnotherPageTransformFactory.cs
Fix for Add another button position
> chore(add another) fix for add another button position

- src/Models/Elements/Summary.cs
- tests/unit-tests/UnitTests/Models/Elements/SummaryTests.cs
> fix(summary): missed a change from PageSlug to PageSummaryId

- src/Helpers/PageHelpers/PageHelper.cs
Reverts smbc-digital/form-builder#530
> Revert "fis(file_upload_key): moved NewGuid() out"

- src/Helpers/PageHelpers/PageHelper.cs
reverted to the ToArray() creation with NewGuid being called, and fixed within that...
> fix(file_upload_key): reverted to original

- tests/unit-tests/UnitTests/Helpers/ActionHelperTests.cs
- tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs
Added test coverage for optional query paramters and verify FileUpload keys are correctly returned and saved in cache
> tests(Helpers)

- src/Models/Elements/Street.cs
- src/Models/Properties/ElementProperties/StreetProperty.cs
- src/Validators/RequiredElementValidator.cs
- src/Views/Shared/Street/StreetSearch.cshtml
> chore(Street): amendments to default text and html structure

- src/Services/MappingService/MappingService.cs
> fix(MappingService): refactor linq into for each so async works

- src/Helpers/PageHelpers/PageHelper.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
Fixed config in Startup using wrong const value
> fix(IOptions): correct config using wrong ConfigValue

- src/Services/MappingService/MappingService.cs
- src/Startup.cs
- src/form-builder.csproj
- tests/unit-tests/UnitTests/Services/MappingServiceTests.cs
- tests/unit-tests/form-builder-tests-unit.csproj
- Remove Wangkanai.Detection package and log message
> chore(packages): Remove device detection package

- src/Constants/StructureConstants.cs
- src/Mappers/Structure/StructureMapper.cs
> refactor(StructureConstants): move models package prefix to a Constant

- README.md
- src/Controllers/Home/HomeController.cs
- src/ViewModels/DataStructureViewModel.cs
- src/Views/Home/DataStructure.cshtml
> chore(DataStructure): update ReadMe

- src/Services/PreviewService/PreviewService.cs
- tests/unit-tests/UnitTests/Services/PreviewServiceTests.cs
> fix(PreviewMode): set expiry time of json

- src/Views/Shared/PreviewMode.cshtml
- src/Views/_ViewImports.cshtml
- Added env check to PreviewMode to create correct url.
> fix(PreviewMode): Added env check for url

- src/Mappers/Structure/StructureMapper.cs
- tests/unit-tests/UnitTests/Mappers/StructureMapperTests.cs
Key wasn't being formatted when trying to get the previously created object
> fix(DataStructure): fix object target mapping being overridden

- src/Constants/LibConstants.cs
- src/Constants/SystemConstants.cs
- src/Services/PreviewService/PreviewService.cs
- src/Validators/IntegrityChecks/FormSchemaIntegrityValidator.cs
- tests/unit-tests/UnitTests/Services/PreviewServiceTests.cs
Added specifiy error message when exception is source is Newstonsoft.Json
> chore(Preivew): Add message when json structure is invalid

- src/Providers/Booking/BookingProvider.cs
- src/Services/SubmitService/SubmitService.cs
- src/SubmissionActions/PostSubmissionAction.cs
- tests/unit-tests/UnitTests/SubmissionActions/PostSubmissionActionTests.cs
- Move booking confirm call before submission call
- Throw error is booking confirm failed.
-  Updated unit test to remove logger
> Booking confirm erorr cancel

- src/Views/Shared/HtmlElements/Inputs/Checkbox/CheckboxOptions.cshtml
> feat(checkbox): add divider for checkbox

- src/ViewModels/PaymentViewModel.cs
- src/Views/Payment/Declined.cshtml
- src/Views/Payment/Failure.cshtml
- Added IsInpreviewMode to Payment View Models
> fix(Payment): Added IsInpreviewMode to ViewData

- src/ViewModels/PaymentViewModel.cs
- src/Views/Payment/Declined.cshtml
- src/Views/Payment/Failure.cshtml
Added IsInPreviewMode to Payment ViewModel
> fix(Views): Added IsInPreviewMode to Payment ViewModel

- src/Builders/ElementBuilder.cs
- src/Models/Elements/Checkbox.cs
- src/Models/Option.cs
- src/Models/Properties/ElementProperties/CheckboxProperties.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/Validators/ExclusiveCheckboxValidator.cs
- src/Validators/IntegrityChecks/Elements/CheckboxElementCheck.cs
- src/Validators/IntegrityChecks/Form/IFormSchemaIntegrityCheck.cs
- src/Views/Shared/HtmlElements/Inputs/Checkbox/CheckboxOptions.cshtml
- tests/unit-tests/UnitTests/Models/Elements/CheckboxTests.cs
- tests/unit-tests/UnitTests/Validators/ExclusiveCheckboxValidatorTests.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/Element/CheckboxElementCheckTests.cs
Implement exclusive checkbox option with validation
> feat(Checkbox): add exclusive options and validation

- src/TagParsers/PaymentAmountTagParser.cs
Added null check on Conditions within behaviours
> fix(PaymentAmountTagParser): Added null check to conditions

- src/TagParsers/PaymentAmountTagParser.cs
Added null check on Behaviours.Conditions
> fix(PaymentAmountTagParser): Added null check to conditions check

- src/Enum/EPaymentCallbackStatus.cs
- src/Enum/EPaymentCallbackType.cs
- src/Services/PayService/PayService.cs
- tests/unit-tests/UnitTests/Services/PayServiceTests.cs
Added log for when payment callback fails
> chore(PayService): Added logs for payment callback

- src/Utils/Startup/ServiceCollectionExtensions.cs
> chore(Extensions): removed dup using

- src/Factories/Transform/UserSchema/BehaviourConditionsPageTransformFactory.cs
Added null check to page.Behaviour Conditions due to Value cannot be null. (Parameter 'source') error.
> fix(PageTransforms): added null check to Conditions

- src/Views/Shared/HtmlElements/Link/Link.cshtml
merge devleop into master to include container div on link
> chore(views): add container div to links

- src/Validators/DateInputWithInRangeValidator.cs
- Fix for within range so it cause validation when it that exact year
> Fix for within date range

- src/Config/appsettings.json
- src/Config/appsettings.prod.json
- src/Config/appsettings.stage.json
- src/Configuration/JavascriptConfiguration.cs
- src/Configuration/StylesheetConfiguration.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/Views/Shared/Error/_ErrorLayout.cshtml
- src/Views/Shared/_Layout.cshtml
Moved stylsheet and js files to configuration to allow overrides between envs.
> refactor: Moved stylsheet and Js to config

- src/Config/appsettings.json
- src/Config/appsettings.prod.json
- src/Config/appsettings.stage.json
- Fix civicapay config for stg/prod
- remove unsued overrides
> fix: amend civicapay gateway config

- tests/structure-tests/cypress/integration/Declaration/snapshots.js
> fix(struct tests): declaration

- tests/structure-tests/README.md
> chore(structure tests): add readme file

- README.md
> chore(readme): update readme with link to structure test wiki

- src/Config/appsettings.int.json
> Int logging

- src/Startup.cs
Removal of AddHttpsRedirection/ForwardedHeadersOptions from startup
> fix: removal of AddHttpsRedirection/ForwardedHeadersOptions

- src/Config/appsettings.int.json
- src/Startup.cs
Add int to UseDeveloperExceptionPage
> chore: add int to UseDeveloperExceptionPage

- src/Config/appsettings.int.json
- src/Startup.cs
Updated cookie policy to prevent issue when running non https but behind ISS/reverse proxy
> Cookie security

- src/Config/appsettings.int.json
Removed logging changes no longer required
> chore: removed int logging config

- src/Helpers/ElementHelpers/ElementHelper.cs
- src/Helpers/ElementHelpers/IElementHelper.cs
- src/Models/Elements/DocumentDownloadButton.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/Validators/IntegrityChecks/Elements/DocumentDownloadButtonCheck.cs
- tests/unit-tests/UnitTests/Helpers/ElementHelperTests.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/Element/DocumentDownloadCheckTests.cs
Add validator for documentDownload if documentType isn't set
> feat(documentDownload): add validation for document type

- src/Services/MappingService/MappingService.cs
Moved the "GetReducedAnswers" above new loop of visited pages on line: 103, to get the true journey the user has taken..
See [comments in Jira card](https://stockportbi.atlassian.net/browse/DIGITAL-7193)
> fix(Mapping_Service): move method call

- tests/structure-tests/snapshots.js
Incremented snapshot version to match one in master
> chore(structure-tests): bump snapshot version number

- src/Services/RetrieveExternalDataService/RetrieveExternalDataService.cs
- tests/unit-tests/UnitTests/Services/RetrieveExternalDataServiceTests.cs
[New Feature - Jira Card DIGITAL-7250](https://stockportbi.atlassian.net/browse/DIGITAL-7250)
**Changed**
-) RetrieveExternalData : Doesn't throw if response is NotFound and the Answer is set to 'Null'
-) RetrieveExternalData unit test to reflect above changes
**Added**
-) unit tests for this feature
> Lookup from answers -Handle status code

- src/Validators/IntegrityChecks/Form/BaseUrlCheck.cs
- tests/unit-tests/UnitTests/Validators/IntegrityChecks/Form/BaseUrlCheckTests.cs
Add checks to skip over requests to Paths "/Preview" or "/FB_PREVIEW_"
> fix(BaseUrlCheck): add check to exclude Preview paths and add unit tests

- src/Extensions/ElementExtensions.cs
- tests/unit-tests/UnitTests/Extensions/ElementExtensionsTests.cs
Added a null check for the ConditionalElementId in Option as not all options will have a conditional element
> fix(ElementExtensions): add null check for ConditionalElementId

- src/Services/RetrieveExternalDataService/RetrieveExternalDataService.cs
-) Bug fix for Null Content for Retrieved External Data
> fix(RetrieveExternalService) Handle null content conrrectly

- src/Builders/ElementBuilder.cs
- src/Models/Properties/ElementProperties/BaseProperty.cs
- src/Validators/DecimalValueValidator.cs
- tests/unit-tests/UnitTests/Validators/DecimalValueValidatorTests.cs
Updated decimal validation message property to 'DecimalValidationMessage'
> chore: changed decimal validation message property

- src/Services/PayService/PayService.cs
-) Moved private method into HandleCallBack and passed the actual payment status to the logger, as it was just one line and it was always being passed a EPaymentCallbackStatus.Failure even though a Success or Declined would still call the HandleCallBack method.
-) Used nameof() to get string version of Service and Method name for logs, as opposed to actual strings
-) Wrapped some logger messages as they were off screen
-) Ran VS Code Cleanup
-) Removed unused "using" statements
-) Removed some whitespace
> chore(PayService): refactor private. rm strings.

- src/Views/Payment/Failure.cshtml
[Jira issue #7660](https://stockportbi.atlassian.net/browse/DIGITAL-7660)
Content change of the Payment Failure page. Needed full stop and then capital letter.
> fix(FailurePage): content - improve grammar

- src/Services/MappingService/MappingService.cs
Update mapping service to include 'Case reference' so it available when posting a request to an API
> feat(mappingService) update mapping to save CaseReference

- tests/unit-tests/UnitTests/Services/PageServicesTests.cs
> revert(PageServiceTests): revert previous change

- src/Validators/RestrictMimeTypeValidator.cs
Bug fix for file upload to allow uppercase extension type
> Docm uppercase bug

- src/Config/appsettings.local.json
> chore(appsettings.local): turn on FakeSubmission

- src/Models/Elements/Summary.cs
- tests/unit-tests/UnitTests/Models/Elements/SummaryTests.cs
> tests(Summary): added an additional unit test

- src/Views/FakePayment/Index.cshtml
> chore(FakePayment): add id's to buttons

- src/Services/StreetService/StreetService.cs
- tests/unit-tests/UnitTests/Services/StreetServiceTests.cs
Small change to enable diagnosis of street search issues
- [x ] Code compiles correctly
- [ x] All tests passing
> minor: update logging and stopwatch on street service

- src/Services/StreetService/StreetService.cs
- tests/unit-tests/UnitTests/Services/StreetServiceTests.cs
Remove debug logs
Fix spelling mistakes
> revert(StreetService): remove stopwatch logging

- src/Views/Payment/CallbackFailure.cshtml
> chore(CallbackFailure): amend endpoint text

- src/Controllers/Home/HomeController.cs
- src/Enum/EBehaviourType.cs
- src/Models/Behaviour.cs
- src/Models/Page.cs
- src/Services/SubmitService/ISubmitService.cs
- src/Services/SubmitService/SubmitService.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/Workflows/RedirectWorkflow/IRedirectWorkflow.cs
- src/Workflows/RedirectWorkflow/RedirectWorkflow.cs
- tests/unit-tests/UnitTests/Controllers/HomeControllerTest.cs
- tests/unit-tests/UnitTests/Services/SubmitServiceTests.cs
- tests/unit-tests/UnitTests/Workflows/RedirectWorkflowTests.cs
This architecture for this functionality is heavily influenced bySubmitAndPay. It works by calling a workflow function that uses the submitService to transform the given redirectURL using tag parsers and finally appending the reference generated by the external service.
- Create new switch case inside HomeController for SubmitAndRedirect.
- Create new 'submit and redirect' workflow.
- Create new RedirectSubmissionFunction in SubmitService that builds up final redirectURL.
- Create new tests and update existing ones.
> Submit and redirect

- src/Constants/ValidateConstants.cs
- src/Services/PageService/PageService.cs
- src/Services/ValidateService/ValidateService.cs
Jira Card - File Upload issue
https://stockportbi.atlassian.net/browse/DIGITAL-8643
-) Update ValidateService to store 'isValidated' key in the cache so we know if the case reference has been validated or not to avoid multiple calls.
To Test
- Upload a file around 3mb and it should error. A small file will not work because the process time when we call aws is too short
> chore(validateService): Add flag so service not called each time when uploading a file

- src/Constants/ValidateConstants.cs
- src/Services/PageService/PageService.cs
- src/Services/ValidateService/ValidateService.cs
> revert branch

- src/Config/appsettings.json
- src/Config/appsettings.qa.json
> fix(appsettings): change to scninthub baseurl

- src/Validators/IntegrityChecks/Elements/BookingElementCheck.cs
> fix(BookingElementCheck): add null check to Lookup Property

- src/form-builder.csproj
- tests/unit-tests/form-builder-tests-unit.csproj
Upgrade to full release of Gateways
> feat(Gateways): upgrade to v11.0.0

- src/ContentFactory/PageFactory/PageFactory.cs
- src/Models/FormSchema.cs
- src/Startup.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/ViewModels/FormBuilderViewModel.cs
- src/Views/Shared/HtmlElements/Footer/Footer.cshtml
- src/Views/Shared/HtmlElements/Header/Header.cshtml
- tests/structure-tests/package-lock.json
- Add embeddable property to FormSchema, ViewModel
- Add check for that property to header, footer view
- Add ConfigureCorsPolicy to Utils with stockport.gov website as accepted URLs
- Add that to the startup
> feat(embeddable): add parameter to formModel, CORS to Utils

- src/Middleware/HeaderConfiguration.cs
Add the test urls to the headers middleware to allow it to be placed in an iframe on the council website in test.
> chore(headers): add dev iag urls to cors

- src/Middleware/HeaderConfiguration.cs
Add a ternary if the environment is not prod or stage, localhost will be appended to the headers to allow for testing of the embeddable form functionality locally on iag-webapp
> chore(headerconfig): add ternary for localhost url env check

- src/Controllers/Payment/FakePaymentController.cs
Make a property readonly so that there is a change to trigger a redeploy
> fix(FakePaymentController): insignificant change to trigger a redeploy

- src/Services/BookingService/BookingService.cs
> chore(BookingService): add 2 cache checks with Exceptions

- src/Services/BookingService/BookingService.cs
> fix(BookingService): add Transform and Parse to ProcessDateAndTime

- src/Views/Shared/_Layout.cshtml
The fakePayment page was erroring due to a null value, changed the ViewData to just pull through from the ViewModel instead which pulls through the appropriate value.
> chore(layout): change viewData to model

- src/Views/Shared/_Layout.cshtml
> chore: code formatting

- src/Services/PayService/PayService.cs
Adds some payment logging so that we can 
1, Identify payments which don't return a success code - but that are potentially successful
2, Identify payment requests and responses and look at any timing/session issues
> patch: adds payment logging to correlate payment requests and responses

- src/Services/PayService/PayService.cs
- src/Services/SubmitService/SubmitService.cs
- tests/unit-tests/UnitTests/Services/SubmitServiceTests.cs
Added some more logging so we can analyse what requests are being made and try and find the source of any duplicates.
> patch(logging) - Add more logging around submission endpoints

- src/Config/appsettings.json
- src/ContentFactory/SuccessPageFactory/SuccessPageFactory.cs
- src/Providers/StorageProvider/DistributedCacheWrapper.cs
- src/Services/MappingService/MappingService.cs
- src/Services/PageService/PageService.cs
- src/Services/PayService/PayService.cs
- src/Startup.cs
- src/Workflows/RedirectWorkflow/RedirectWorkflow.cs
- tests/unit-tests/UnitTests/ContentFactory/SuccessPageContentFactoryTests.cs
- tests/unit-tests/UnitTests/Services/MappingServiceTests.cs
- tests/unit-tests/UnitTests/Services/PageServicesTests.cs
- tests/unit-tests/UnitTests/Workflows/RedirectWorkflowTests.cs
Increase the amount of logging to see if we can find where/why sessions are null and if that is just a session length/timing issue - also increase session and cache times to 60 mins
- [ x Created tests for the new changes
> minor: updates to logging and increase session/cache times

- src/Controllers/Payment/PaymentController.cs
- src/Services/PageService/PageService.cs
- src/Services/SubmitService/SubmitService.cs
- tests/unit-tests/UnitTests/Controllers/PaymentControllerTests.cs
- tests/unit-tests/UnitTests/Services/PageServicesTests.cs
> patch: push more logging

- src/Config/appsettings.json
- src/Providers/StorageProvider/DistributedCacheWrapper.cs
- [] Created tests for the new changes
> patch: fix incorrect expiration in distributed cache helper

- tests/structure-tests/cypress.config.js
> fix(cypress.config.js): increase timeout allowance

- src/Factories/Transform/UserSchema/AddAnotherPageTransformFactory.cs
- tests/unit-tests/UnitTests/Factories/Transform/AddAnotherPageTransformFactoryTests.cs
The GDS complained when using double nested conditionally revealed questions so changing the delimiter
> fix(AddAnother): swap delimiter from : to _ for GDS compatibility

- src/Builders/ElementBuilder.cs
- src/Factories/Transform/UserSchema/AddAnotherPageTransformFactory.cs
- src/Models/Elements/Checkbox.cs
- src/Models/Properties/ElementProperties/BaseProperty.cs
- src/Views/Shared/DateInput/DateInput.cshtml
- src/Views/Shared/DatePicker/DatePicker.cshtml
- src/Views/Shared/HtmlElements/Inputs/Radio/Radio.cshtml
- src/Views/Shared/HtmlElements/Inputs/Radio/RadioOptions.cshtml
- src/Views/Shared/HtmlElements/Textarea/Textarea.cshtml
- src/Views/Shared/HtmlElements/Textbox/Textbox.cshtml
- src/Views/Shared/TimeInput/TimeInput.cshtml
- tests/unit-tests/UnitTests/Factories/Transform/AddAnotherPageTransformFactoryTests.cs
added SetAutofocus and Autofocus fields in BaseProperty to fix the AddAnother focus issue, so when a new element is added the focus is on the new element
> Add another fix

- src/Helpers/PageHelpers/PageHelper.cs
- tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs
> fix(PageHelper): fix remove button for AddAnother element

- src/Services/MappingService/MappingService.cs
> fix(AddAnother): fix Target Mapping for changed separater

- src/Services/MappingService/MappingService.cs
> revert(MappingService): revert change

- src/Models/EmailMessage.cs
- src/TagParsers/FormAnswerTagParser.cs
- src/Validators/DateInputIsFutureDateAfterRelativeValidator.cs
- src/Validators/DateInputIsFutureDateBeforeRelativeValidator.cs
- tests/unit-tests/UnitTests/Services/EmailSubmitServiceTests.cs
- tests/unit-tests/UnitTests/Validators/DateInputIsFutureDateAfterRelativeValidator.cs
- tests/unit-tests/UnitTests/Validators/DateInputIsFutureDateBeforeRelativeValidator.cs
> Submit email tests

- src/Services/EmailSubmitService/EmailSubmitService.cs
- src/TagParsers/FormAnswerTagParser.cs
> Submit email subject

- src/Builders/ElementBuilder.cs
- src/Models/Properties/ElementProperties/DateProperty.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/Validators/DateInputIsPastDateBeforeRelativeValidator.cs
- tests/unit-tests/UnitTests/Validators/DateInputIsPastDateBeforeRelativeValidator.cs
Added the 'Is past date before relative' validator functionality for the date input element.
> feat(Date Input): add IsPastDateBeforeRelativeValidator validator

- src/Config/appsettings.json
- src/Configuration/PowerAutomateConfiguration.cs
- src/Models/PowerAutomateDetails.cs
- src/Services/EmailSubmitService/EmailSubmitService.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- tests/unit-tests/UnitTests/Services/EmailSubmitServiceTests.cs
Small addition to the submitanemail method to log an event in a datalist. this way we have a simple and basic way of knowing ig emails are being sent and in what volume.  It uses a power automate to write to the datalist.
> Submit and email logs

- src/Config/appsettings.json
- src/Configuration/PowerAutomateConfiguration.cs
- src/Models/PowerAutomateDetails.cs
- src/Services/EmailSubmitService/EmailSubmitService.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- tests/unit-tests/UnitTests/Services/EmailSubmitServiceTests.cs
* chore(emailsubmit): logging to a flow
* chore(submitandemail): logging and tests
* chore(submitandemail): comment suggestions
* chore(submitandemail): comment suggestions
> Submit and email logs (#907)

- src/Services/SubmitService/SubmitService.cs
> fix(SubmitService): amend missed-bin-collection log data value

- src/Services/MappingService/MappingService.cs
- src/Services/SubmitService/SubmitService.cs
> chore(Logs): remove 2 logs, add new log to log raw cached session data

- src/Helpers/PageHelpers/PageHelper.cs
- src/Services/MappingService/MappingService.cs
- tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs
> chore(Logs): remove logs, add logs around SaveAnswers for missed bin

- src/Helpers/PageHelpers/PageHelper.cs
> chore(PageHelper): move log earlier

- src/Builders/ElementBuilder.cs
- src/Config/appsettings.local.json
- src/Constants/StreetConstants.cs
- src/Models/Properties/ElementProperties/StreetProperty.cs
- src/Views/Shared/Street/StreetSelect.cshtml
> Street hint

- src/Helpers/ActionsHelpers/ActionHelper.cs
> fix(actionHelper): add null check to answer retrieval for actionhelper

- src/Config/appsettings.local.json
> fix(settings): change fake submission to true

- src/Helpers/PageHelpers/PageHelper.cs
> chore(PageHelper): add wait after GetCache in SaveAnswers

- src/Helpers/PageHelpers/PageHelper.cs
> chore(PageHelper): add wait after GetCache in SaveAnswers (#928)

- src/Helpers/PageHelpers/PageHelper.cs
> chore(PageHelper): add a word to trigger another build

- src/Services/PageService/PageService.cs
- tests/unit-tests/UnitTests/Services/PageServicesTests.cs
> Sessions - update to enable session logging and determine whether sessions are being terminated early

- src/Middleware/SessionLoggingMiddleware.cs
- src/Startup.cs
Fixes issue with session logging middleware not logging correctly
> chore(session middleware): move middleware registration

- src/Middleware/SessionLoggingMiddleware.cs
> fix(middleware): exclude requests to healthcheck from logging

- src/Services/PageService/PageService.cs
Attempting to fix issue with massh for session handling introdued in previous commit
> fix(session issue) - move retrieval of session out of constructor

- src/Services/PageService/PageService.cs
> fix(session issue) - move retrieval of session out of constructor (#959)

- src/Middleware/SessionLoggingMiddleware.cs
- src/Services/PageService/PageService.cs
> Sessions fix

- src/Controllers/Home/HomeController.cs
- src/Services/PageService/PageService.cs
- tests/unit-tests/UnitTests/Controllers/HomeControllerTest.cs
> Sessions fix - enables session data logging in controller and adds logs. 

- src/Services/AddressService/AddressService.cs
- tests/unit-tests/UnitTests/Services/AddressServiceTests.cs
> chore(addressservice): logs

- src/Services/AddressService/AddressService.cs
> fix(AddressService): add nullable

- src/Services/OrganisationService/OrganisationService.cs
- src/Services/StreetService/StreetService.cs
> hotfix(Street and Organisation)

- src/Models/OSProperty.cs
- src/Providers/Address/OSPlacesAddressProvider.cs
> chore(OSPlaces): further neaten up of response

- .github/workflows/dotnet-core.yml
> chore(git yml): actions upgrade to ver 4

- src/Config/appsettings.int.json
> chore(appsettings): turn fake payments on in INT

- src/Middleware/HeaderConfiguration.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
> chore(middleware/startup): CSP adding for int Stockroom

- src/Config/appsettings.int.json
> chore(appsettings int): turn off fake payments

- src/Config/appsettings.local.json
- src/Helpers/Cookie/CookieComplianceHelper.cs
- src/Helpers/Cookie/ICookieComplianceHelper.cs
- src/Middleware/CookiesComplianceMiddleware.cs
- src/Models/CookieConsentLevel.cs
- src/Startup.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/Views/Shared/Cookie/CookieBanner.cshtml
- src/Views/Shared/HtmlElements/Footer/Footer.cshtml
- src/Views/Shared/TagManager/TagManagerHead.cshtml
- src/Views/Shared/_Layout.cshtml
- src/wwwroot/assets/css/cookie-notice.css
> Cookie notice fix

- src/Views/Embedded/Index.cshtml
- src/Views/Shared/_Layout.cshtml
- src/wwwroot/assets/css/form-builder.css
> chore(Embedded): move script and styles to partial

- src/Views/Embedded/Index.cshtml
> chore(Embedded): update script to work with array of allowed origins

- src/Views/Embedded/Index.cshtml
> chore(Embedded): add console logs

- src/Views/Embedded/Index.cshtml
- src/Views/Shared/_Layout.cshtml
> chore(Layout): move script to confirm it's working

- src/Views/Shared/_Layout.cshtml
> chore(Layout): change to using string instead of array

- src/Views/Shared/_Layout.cshtml
> chore(Layout): add extra console.log

- src/Views/Shared/_Layout.cshtml
> chore(Layout): update script to sent height

- src/Views/Shared/_Layout.cshtml
> chore(Layout): cleanup script

- src/Views/Embedded/Index.cshtml
- src/Views/Shared/_Layout.cshtml
> chore(Layout/Index): move script to partial

- src/Middleware/HeaderConfiguration.cs
- src/Utils/Startup/ServiceCollectionExtensions.cs
- src/Views/Embedded/Index.cshtml
> chore(HeaderConf/Index): cleanup + add stockroom to CSP

- src/Views/Embedded/Index.cshtml
> chore(Embedded): update script to use referrer instead of window.location + add extra console.logs

- src/Views/Embedded/Index.cshtml
> chore(Embedded): remove console.log

- src/Views/Embedded/Index.cshtml
> chore(Embedded): add content loaded event listener

- src/Middleware/HeaderConfiguration.cs
> chore(HeaderConfiguration): remove / from stockroom links

- src/Startup.cs
> chore(Startup): set cookie SameSite to None

- src/Startup.cs
> chore(Startup): change SecurePolicy to SameAsRequest

- src/Startup.cs
> chore(Startup): revert cookie antiforgery change

- src/Controllers/Home/HomeController.cs
- src/Models/EnvironmentAvailability.cs
- src/Services/PageService/PageService.cs
- src/ViewModels/FormBuilderViewModel.cs
- src/Views/Home/Unavailable.cshtml
- tests/unit-tests/UnitTests/Controllers/HomeControllerTest.cs
- tests/unit-tests/UnitTests/Services/PageServicesTests.cs
> feat(Unavailable): page for unavailable forms

- src/Views/Shared/Booking/CalendarDay.cshtml
- src/Views/Shared/Booking/CalendarHeader.cshtml
- src/Views/Shared/Time/TimePeriod.cshtml
> chore(Calendar): improvements to Calendar accessibility
