src/Views/Shared/H3.cshtml
Fixed h3 view not using cssclass variable
=> fix(H3): Use cssClass varible for classname

src/Models/Elements/AddressManual.cs
Fixed IsPostCodeValid to check PostcodeValidationMessage,
Removed IsValid from all line isValid checks as would append validation error if another address line was invalid.
=> fix(DIGITAL-2072): Validation errors within AddressManual

src/Views/Shared/_Layout.cshtml
- Added rel="noreferrer noopener" to feedback banner anchor to reduce the risk of reverse tabnabbing
https://owasp.org/www-community/attacks/Reverse_Tabnabbing
=> feat(Layout): Added rel to feedback link to reduce the risk of reverse tabnabbing

src/Validators/EmailElementValidator.cs
Amend email Regex to allow emails with multiple .'s after the ~ with an many characters as needed.
=> fix: amend email Regex

src/Models/Elements/Textbox.cs
Fixed spellecheck on TextBox not working due to missing lowercase on bool value
=> fix(spellcheck): spellcheck on textbox

src/Extensions/FormAnswersExtensions.cs, tests/UnitTests/Extensions/FormAnswersExtensionsTests.cs
Updated GetReducedAnswers method to FindAll on pages to fix issue with not correctly creating answers when formSchema contains multiple pages with the same pageslug.
=> chore(GetReducedAnswers): added support for multiple pages with same pageslug

src/Factories/Transform/ReusableElements/ReusableElementSchemaTransformFactory.cs, tests/UnitTests/Factories/Transform/ReusableElementSchemaTransformFactoryTests.cs
Added ability to allow you to override default maxlength for reusable elements
=> chore: Added maxlength override for reusable elements

src/Builders/ElementBuilder.cs, src/Factories/Transform/ReusableElements/ReusableElementSchemaTransformFactory.cs, tests/UnitTests/Factories/Transform/ReusableElementSchemaTransformFactoryTests.cs
Added ability to allow override for hint and custom validation message within reusable elements
=> chore: Added hint and custom validation message override for reusable elements

src/Constants/ValidationConstants.cs, src/Validators/EmailElementValidator.cs
Changed Email validation message to not allow override and to be always the govuk error message.
"Enter an email address in the correct format, like name@example.com"
=> fix: email validation message

src/Factories/Transform/ReusableElements/ReusableElementSchemaTransformFactory.cs, tests/UnitTests/Factories/Transform/ReusableElementSchemaTransformFactoryTests.cs
Updated reusable element factory to support pages with the same page-slug, the page index is now used rather then the page slug.
=> feat: resuable elements multiple pages

src/Extensions/StringExtensions.cs, src/Mappers/ElementMapper.cs, tests/UnitTests/Extensions/StringExtensionsTests.cs, tests/UnitTests/Mappers/ElementMapperTests.cs
Limit filename length in submit data to 100 characters.
=> chore(MappingService): limit filename to 100 characters

tests/UnitTests/Validators/MultipleFileUploadElementValidatorTests.cs
Remove extra using in MultipleFileUploadElementValidatorTests to ensure we have no warnings
=> chore: remove extra using in MultipleFileUploadElementValidatorTests

src/Constants/SystemConstants.cs, src/Extensions/StringExtensions.cs, src/Models/Elements/FileUpload.cs, src/Models/Elements/MultipleFileUpload.cs, src/Validators/MultipleFileUploadElementValidator.cs, src/Validators/RestrictCombinedFileSizeValidator.cs, src/Validators/RestrictFileSizeValidator.cs, tests/UnitTests/Models/Elements/MultipleFileUploadTests.cs
Changed how file size is determine by using 1MB in binary bytes value.
1 MB = 1,048,576 Bytes
=> fix(fileupload): changed file size check to use binary bytes value

src/Helpers/PageHelpers/PageHelper.cs, src/Services/FileUploadService/FileUploadService.cs, tests/UnitTests/Helpers/PageHelperTests.cs, tests/UnitTests/Services/FileUploadServiceTests.cs
Fixed issue with optional fileupload when on last page of form and no files uploaded routing would fail due to using previous page for routing logic as no data has been saved.
=> fix(fileupload): optional fileupload now save answers

src/Constants/BookingConstants.cs, src/Helpers/ActionsHelpers/ActionHelper.cs, src/Models/Actions/UserEmail.cs, src/TagParsers/FormAnswerTagParser.cs, src/TagParsers/FormDataTagParser.cs, src/TagParsers/TagParser.cs, src/Views/Shared/Booking/CheckYourBooking.cshtml
Select dynamic variables to use in the email body
Created a very similar method to TagParsers, to allow {{variables}} within the FormBuilders, PageActions of Type UserEmail, "Content" field. So that variables from he form can be used in the email body. These variables for the booking element are taken from BookingConstants, and created from searched and reserved dates / appointments.
This was brought to my attention by Stephen. That the end-date of the appointment would be needed in the confirmation email.
My concern is that this I totally have the wrong end of the stick, and this has already been done somewhere else. I couldn't find any other email functionality within the application, apart from this PageActions. So this is what I did...
Some clean up / standardisation in a few files... …
=> chore(booking):Add Email Content Method

src/Views/Home/Index.cshtml
When a user is using the Booking calendar on occassions the page may not have fully loaded and if the user clicks on the previous/next month button the request sent to the controller does not contains the AntiForgeryToken due to being at the bottom of the form. 
We now generate the AntiForgeryToken token at the top of the form before the elements html is rendered.
=> fix(Views): Handle AntiForgeryToken generation

src/Providers/EmailProvider/FakeEmailProvider.cs, tests/unit-tests/UnitTests/Helpers/ActionHelperTests.cs, tests/unit-tests/UnitTests/Services/EmailServiceTests.cs, tests/unit-tests/UnitTests/TagParsers/TagParserTests.cs
Calls Email Content Method && Email Content Parses Variable or removes Variable from content string
Added Tests for Method I created to parse variables passed into an Email Body from the properties.content field in the JSON form.
1) EmailServiceTests : Check it calls the GetEmailContent method.
2) ActionHelpertests : Check it finds the response from the form by a valid QuestionId, or removes the variable from the properties.content field which makes up the body of the email, if the {{variable}} name is invalid/type/etc.
3) And some small changes for constructors that I come across with a single argument, moved to arrow style initialisation.
=> tests(email_content): test email

src/Startup.cs
Attempt number two at a fix for middleware warning log "Failed to determine the https port for redirect."
couple ways to do this could of set it in appsettings.json also went adding it in ConfigureServices
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#port-configuration
=> chore(prject): added https redirect

src/Startup.cs
Attempt number three at a fix for middleware warning log "Failed to determine the https port for redirect." with ForwardHeaders for load balancer 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1
couple ways to do this could of set it in appsettings.json also went adding it in ConfigureServices
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#port-configuration
=> chore(startup): added redriect with forwarded headers

src/Models/Properties/ElementProperties/LinkProperty.cs, src/Views/Shared/ChevronSVG.cshtml, src/Views/Shared/DocumentUpload.cshtml, src/Views/Shared/Link.cshtml
Updated link element to support ability to enabled right chevron within element.
This is done via the DisplayRightChevron property
https://github.com/smbc-digital/form-builder/wiki/Link
=> feat(Link): added support for right chevron

src/Services/PageService/PageService.cs, tests/unit-tests/UnitTests/Services/PageServicesTests.cs
Throw application exception when session data is null, rather then attempt to Deserialise null object.
Removes error log around attempting to Deserialise a null object.
=> chore(service): throw exception when session data is null

src/Controllers/Document/DocumentController.cs, src/Views/Document/Expired.cshtml
Document download expired view has been missed when updating to DS.
View has been updated and fixed due to missing ViewModel values causing expired view to not be displayed.
=> fix(Document): fixed expired view for document download

src/Builders/ElementBuilder.cs, src/Config/appsettings.local.json, src/Helpers/PageHelpers/PageHelper.cs, src/Models/Properties/ElementProperties/BookingProperty.cs, src/Properties/launchSettings.json, src/Services/BookingService/BookingService.cs, src/Services/MappingService/IMappingService.cs, src/Services/MappingService/MappingService.cs, src/form-builder.csproj, tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs, tests/unit-tests/UnitTests/Services/BookingServiceTests.cs, tests/unit-tests/UnitTests/Services/MappingServiceTests.cs, tests/unit-tests/form-builder-tests-unit.csproj
- update Gateways to v6.0.0
- add CustomerAddressId property to Booking to refer to address questionId
- rename and refactor MappingService.GetCustomerBookingDetails to handle address as a string
- remove MappingService.MapAddress as no longer needed
- move GetReservedBookingLocation call in BookingService to after Reserve to enable use of the BookingRequest object
- refactor GetReservedBookingLocation to use BookingRequest object
- refactor schema validation as email not mandatory anymore
- add unit test to MappingServiceTests for address
=> refactor(customer address): handle address as Address component or text field

src/Models/Elements/Summary.cs
Fix siteimprove issue due to visually hidden span not within the Change acnhor, causing the site imrpove error due to repeated links with the same 'Change' text.
span has been moved within anchor to fix issue.
=> fix(DIGITAL-4496): summary list html structure

src/Views/Shared/Recaptcha/Recaptcha.cshtml, src/Views/Shared/_Layout.cshtml
- Moved recapcha script to partial to only be loaded when required
- Fixed recapcha IE issue which was breaking other JS (Maps) when loaded first
=> fix(Recapcha): load recapha script only when required

src/Models/Actions/IAction.cs
Fixed serialisation issue with IAction type due to JsonSubTypes needing string name not enum. Added string enum converter to convert enum to string version to allow deserialisation once stored in cache.
=> fix(Action): Added jsonconvert attribute to EActionType for JsonSubTypes

src/Views/Shared/Declaration/Declaration.cshtml
- Fixed accessibiity issue with declaration when aria-describedby always had a hint associated with input even when not supplied.
- Refactored view to remove redundent if else
- Added optional text to associated label which was missing originally
=> fix(Declaration): fixed accessibility issue associated with hint

src/Builders/AppointmentTypeBuilder.cs, src/Builders/ElementBuilder.cs, src/Extensions/ListExtension.cs, src/Helpers/PageHelpers/PageHelper.cs, src/Models/AppointmentType.cs, src/Models/Properties/ElementProperties/BookingProperty.cs, src/Services/BookingService/BookingService.cs, src/Services/MappingService/MappingService.cs, tests/unit-tests/Builders/AppointmentTypeBuilder.cs, tests/unit-tests/UnitTests/Extensions/ListExtensionsTests.cs, tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs, tests/unit-tests/UnitTests/Models/Elements/BookingTests.cs, tests/unit-tests/UnitTests/Services/BookingServiceTests.cs, tests/unit-tests/UnitTests/Services/MappingServiceTests.cs
Updated structure for apointment type within booking element to allow for different values across environments. Additionally to this moved OptionalResoucres to allow for different values within env aswell.
Updated wiki:
https://github.com/smbc-digital/form-builder/wiki/Booking
**old**
```json
{
"Type": "Booking",
"Properties": {
"AppointmentType":"0000-0000-0000-0000-0000",
"OptionalResources": [
{
"ResourceId": "0000-0000-0000-0000-0000",
"Quantity": 1
}
]
}
},
```
**new**
```json
{
"Type": "Booking",
"Properties": {
"AppointmentTypes": [
{
"Environment": "local",
"AppointmentId":"0000-0000-0000-0000-0000",
"OptionalResources": [ 
{
"ResourceId": "0000-0000-0000-0000-0000",
"Quantity": 1
}
]
}
]
}
},
```
=> refactor(booking): support for different envs in appointment type

src/Providers/SchemaProvider/S3FileSchemaProvider.cs, src/Providers/Transforms/Lookups/S3LookupTransformDataProvider.cs, src/Providers/Transforms/PaymentConfiguration/S3PaymentConfigurationTransformDataProvider.cs, src/Providers/Transforms/ReusableElements/S3ReusableElementTransformDataProvider.cs
Changed to deserialse from stream when calling json from S3 Buckets
You can test by editing the line of the schema provider
1) Service Collection Extensions > AddSchemaProvider > change "local" to use S3FileSchemaProvider
2) Then edit line S3FileSchemaProvider -Line 51:  var s3Result = await _s3Gateway.GetObject("forms-storage", $"Int/{_configuration["ApplicationVersion"]}/{schemaName}.json");
3) Load up a few forms and check it works...
=> feat(deserialise_form_stream): S3 as Stream

src/Validators/IntegrityChecks/Form/DynamicLookupChecks.cs, tests/unit-tests/UnitTests/Validators/IntegrityChecks/Form/DynamicLookupCheckTests.cs
Fix dynamic lookup incorrect checking LookupSource where not null, rather then being null.
=> fix(IntegrityCheck): fixed check on lookupsources

src/Builders/ElementBuilder.cs, src/Factories/Transform/ReusableElements/ReusableElementSchemaTransformFactory.cs, src/Models/Elements/Address.cs, src/Models/Elements/Booking.cs, src/Models/Elements/Element.cs, src/Models/Elements/Map.cs, src/Models/Elements/Organisation.cs, src/Models/Elements/Street.cs, src/Models/Properties/ElementProperties/BaseProperty.cs, tests/unit-tests/UnitTests/Factories/Transform/ReusableElementSchemaTransformFactoryTests.cs, tests/unit-tests/UnitTests/Models/Elements/AddressTests.cs, tests/unit-tests/UnitTests/Models/Elements/BookingTests.cs, tests/unit-tests/UnitTests/Models/Elements/ElementTests.cs, tests/unit-tests/UnitTests/Models/Elements/MapTests.cs, tests/unit-tests/UnitTests/Models/Elements/OrganisationTests.cs, tests/unit-tests/UnitTests/Models/Elements/StreetTests.cs
Added new element property `SummaryLabel` to allow designs to override the label displayed on the summary page.
=> feat(summary): ability to allow custom labels to be used on summary

src/Builders/ElementBuilder.cs, src/Helpers/ElementHelpers/ElementHelper.cs, src/Helpers/ElementHelpers/IElementHelper.cs, src/Helpers/PageHelpers/PageHelper.cs, src/Models/Elements/Checkbox.cs, src/Models/Elements/Radio.cs, tests/unit-tests/UnitTests/Helpers/ElementHelperTests.cs, tests/unit-tests/UnitTests/Models/Elements/CheckboxTests.cs, tests/unit-tests/UnitTests/Models/Elements/RadioTests.cs
Moved OrderOptions property check into Element helper which is now called within Radio/Checkbox render method
=> fix(OrderBy): OrderBy only runs on Radio/Checkbox

src/Providers/SchemaProvider/S3FileSchemaProvider.cs, tests/unit-tests/UnitTests/Providers/SchemaProvider/S3FileSchemaProviderTests.cs
Updated `IndexSchema` to index the schemas without the bucker prefix and change  `ValidateSchemaName` to do an equal comparison rather then contains. 
This change has been done due to an issue where if u had a form with the name `track-a-report`, in theory requesting the form `a` would work or `report` as it was contains previously.
=> refactor(SchemaProvider): Modified ValidateSchemaName to do an equal check not contains on SchemaName

src/Builders/ElementBuilder.cs, src/Models/Elements/Summary.cs, src/Models/Properties/ElementProperties/SummaryProperty.cs, src/Utils/Startup/ServiceCollectionExtensions.cs, src/Validators/IntegrityChecks/Form/SummaryElementFormCheck.cs, src/ViewModels/SummarySectionViewModel.cs, src/ViewModels/SummarySectionsViewModel.cs, src/Views/Shared/Summary/Summary.cshtml, tests/unit-tests/UnitTests/Models/Elements/SummaryTests.cs, tests/unit-tests/UnitTests/Validators/IntegrityChecks/Form/SummaryElementFormCheckTests.cs
Allow designs to split up the summary into sections via a new property called `Sections`
Refactored Summary RenderAsync to use razor view render to bring inline with other elements.
[Wiki entry](https://github.com/smbc-digital/form-builder/wiki/Summary)
=> Summary sections

src/Constants/BookingConstants.cs, src/Models/AppointmentType.cs, src/Models/Elements/Booking.cs, src/Services/BookingService/BookingService.cs, src/Validators/IntegrityChecks/Elements/BookingElementCheck.cs, src/Views/Shared/Booking/Booking.cshtml, src/Views/Shared/Booking/CheckYourBooking.cshtml, tests/unit-tests/Builders/AppointmentTypeBuilder.cs, tests/unit-tests/UnitTests/Models/Elements/BookingTests.cs, tests/unit-tests/UnitTests/Services/BookingServiceTests.cs, tests/unit-tests/UnitTests/Validators/IntegrityChecks/BookingElementCheckTests.cs
- add reservedBookingAppointmentId to view model and model
- add check in BookingService Reserve for AppointmentId and ReservedAppointmentId
- update BookingService unit tests
- add checks to BookingElementCheck for
- neither AppointmentId or AppointmentIdKey set
- both AppointmentId and AppointmentIdKey set
- refactor BookingElementCheckTests to include new checks and split out Theory into single tests
=> refactor(booking appointment types from previous answer)

src/Helpers/PageHelpers/PageHelper.cs, src/Models/Page.cs, src/Views/Shared/HtmlElements/Headings/H1.cshtml
For elements which require '(optional)' to be displayed in the H1 Title when HideTitle is false
- Add Property to Page 'DisplayOptionalInTitle' - defaults to false
- In PageHelper GenerateHtml, H1 Property Optional will be set using the Page.DisplayOptionalInTitle
- In H1.cshtml '(optional)' will be added if Property.Optional is true
=> refactor(H1 Title): Allow (optional) to be added to Title

src/Views/Shared/Error/_ErrorLayout.cshtml, src/Views/Shared/_Layout.cshtml
Removed media="print" from fav icon, causing issue with chrome browsers requesting /favicon.ico
=> fix(Layout): Remove media print due to chrome issue resolving icon

src/Validators/IntegrityChecks/Form/HasDuplicateQuestionIdsCheck.cs, tests/unit-tests/UnitTests/Validators/IntegrityChecks/Form/HasDuplicateQuestionIdsCheckTests.cs
Add loop around any nested elements to the duplicateId check
=> fix(HasDuplicateQuestonIdsCheck): add support for checking nested elements as well

src/Services/AddAnotherService/AddAnotherService.cs, tests/unit-tests/UnitTests/Services/AddAnotherServiceTests.cs
If a user manages to somehow bypass the Schema generation to attempt to add more fieldsets than they are allowed, an extra check in the AddAnotherService ProcessAddAnother will throw an exception
=> refactor(AddAnother): add Exception for maxFieldsets being exceeded

src/Models/Elements/Textarea.cs, tests/unit-tests/UnitTests/Models/ElementTests.cs, tests/unit-tests/UnitTests/Models/Elements/TextAreaTests.cs
If you provided a maxlenght of below 200 the textarea would not add the rows property correctly, and would look like a textbox. The logic has been changed so that it will now always be rows: 5 and rows:15 if the maxlength is greater than 500.
=> chore(TextArea): Amended Textarea rows property

src/Models/Properties/ActionProperties/RetrieveExternalDataActionProperty.cs, src/Services/RetrieveExternalDataService/RetrieveExternalDataService.cs, tests/unit-tests/UnitTests/Services/RetrieveExternalDataServiceTests.cs
Added (bool)IncludeInFormSubmission property to BaseProperties of IAction for RetrieveExternalDataActionProperty.cs
This will be handled in RetrieveExternalDataService.cs line: 92
If true, we save the (QuestionId)key-value pair to FormAnswers.AdditionalFormData
If duplicate keys exist, we remove and re-add the value ( This may come in if a user backs up on the form journey )
AdditionalFormData already get's resolved in the Mapping Service Create post Data, so the values that are retrieved externally are now within the submission post data object
Add unit tests
=> External data mapping

src/Helpers/PageHelpers/PageHelper.cs
Moved the NewGuid() method out into a sperate line
Found the behaviour previously was calling the NewGuid() creation each time the key was requested
=> fis(file_upload_key): moved NewGuid() out

src/Helpers/PageHelpers/PageHelper.cs, src/Mappers/ElementMapper.cs, src/Providers/FileStorage/InMemoryStorageProvider.cs, src/Services/FileUploadService/FileUploadService.cs, tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs
refactor as mentioned the other day... to make reading code a little clearer and clean up extra bits.
Pagehelper.SaveFormFileAnswers:
-) moved all the stuff about elementAt(index) into a foreach loop
-) renamed linq foreach anonymous variable from "file" to "group"
-) Removed a couple of ".ToList()" calls
Mappers.ElementMapper:
-) C# 9 new()
-) inverted if null check
-) removed extra ".ToList()" call
FileStorage.InMemoryFileStorageProviser:
-) moved to expression bodied constructor
FileUploadService:
-) removed extra ".ToList()"
-) removed parenthesis around linq foreach anonymous variable
PageHelperTests:
-) C# 9
=> chore(refactor_file_uploads): refactor

src/Extensions/FormSchemaExtensions.cs, src/Factories/Schema/ISchemaFactory.cs, src/Factories/Schema/SchemaFactory.cs, src/Factories/Transform/UserSchema/AddAnotherPageTransformFactory.cs, src/Factories/Transform/UserSchema/DynamicLookupPageTransformFactory.cs, src/Factories/Transform/UserSchema/IUserPageTransformFactory.cs, src/Helpers/ActionsHelpers/ActionHelper.cs, src/Services/DocumentService/DocumentSummaryService.cs, src/Services/PageService/PageService.cs, src/Workflows/DocumentWorkflow/DocumentWorkflow.cs, src/Workflows/SuccessWorkflow/SuccessWorkflow.cs, tests/unit-tests/UnitTests/Controllers/BookingControllerTests.cs, tests/unit-tests/UnitTests/Extensions/FormSchemaExtensionsTests.cs, tests/unit-tests/UnitTests/Factories/Schema/SchemaFactoryTests.cs, tests/unit-tests/UnitTests/Factories/Transform/AddAnotherPageTransformFactoryTests.cs, tests/unit-tests/UnitTests/Factories/Transform/DynamicLookupPageTransformFactoryTests.cs, tests/unit-tests/UnitTests/Helpers/ActionHelperTests.cs, tests/unit-tests/UnitTests/Services/BookingServiceTests.cs, tests/unit-tests/UnitTests/Services/DocumentSummaryServiceTests.cs, tests/unit-tests/UnitTests/Services/MappingServiceTests.cs, tests/unit-tests/UnitTests/Services/PageServicesTests.cs, tests/unit-tests/UnitTests/Services/SubmitServiceTests.cs, tests/unit-tests/UnitTests/Workflows/SuccessWorkflowTests.cs
- Create TransformPage method in SchemaFactory
- Call TransformPage on ProcessPage
- All journey pages if Summary
- Current page if not Summary
- Call TransformPage on ProcessRequest for current page
- Call TransformPage on DocumentDownload creation
- Create GetReducedPages Extension method to get pages for users journey
- Remove GetSession calls from UserPageTransform methods
- Remove saving DynamicOptions to cache
- Update and add new unit tests
=> refactor(UserPageTransforms): refactor to only do when needed

src/Models/Elements/Address.cs, src/Models/Properties/ElementProperties/AddressProperty.cs, src/Views/Shared/Address/AddressManual.cshtml, src/Views/Shared/Address/AddressSelect.cshtml
Amendments to:
- default SelectLabel (Address only)
- Cannot find address in list
- Address not found inset text
- Handle NoManualAddressDetailText Property as Html.Raw
=> chore(Address): amendments to default text values for Address pattern

src/Models/Elements/MultipleFileUpload.cs, tests/unit-tests/UnitTests/Models/Elements/MultipleFileUploadTests.cs
Moved Parenthesis to correct wrap filesize calculation
=> fix(MultiFileUpload): fixed logic in checking max file size

src/Configuration/AwsSesKeysConfiguration.cs, src/Configuration/CivicaPaymentConfiguration.cs, src/Configuration/DistributedCacheExpirationConfiguration.cs, src/Configuration/FileStorageProviderConfiguration.cs, src/Configuration/FormConfiguration.cs, src/Configuration/HashConfiguration.cs, src/Configuration/ReCaptchaConfiguration.cs, src/Configuration/SubmissionServiceConfiguration.cs, src/Helpers/PageHelpers/PageHelper.cs, src/Providers/FileStorage/s3FileStorageProvider.cs, src/Services/FileUploadService/FileUploadService.cs, src/Services/PageService/PageService.cs, src/Utils/Startup/ServiceCollectionExtensions.cs, tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs, tests/unit-tests/UnitTests/Providers/FileStorage/S3FileStorageProviderTests.cs, tests/unit-tests/UnitTests/Services/FileUploadServiceTests.cs, tests/unit-tests/UnitTests/Services/PageServicesTests.cs
- Changed how IOptions are registered in startup to be the same via a const ConfigValue within the Configuration object across all IOptions
- Removed IConfiguration from some servives/helpers for just the IOptions it requires
- Do selection of IFileStorageProvider within Constructor, as FileStorageProvider does not change per form like Lookups, is singular.
=> refactor(Config): Moved parsing config to IOptions, removed IConfiguration

src/Helpers/PageHelpers/IPageHelper.cs, src/Helpers/PageHelpers/PageHelper.cs, src/Services/PageService/PageService.cs, tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs, tests/unit-tests/UnitTests/Services/PageServicesTests.cs
- Add SanitizeViewModel method to PageHelper to remove whitespace from string inputs
- Amend ProcessRequest in PageService to call SanitizeViewModel
- Update and add unit tests
I have nested the checks to avoid getting the Value type for viewModel items we are disallowing, but happy to combine the check if people feel it won't be a significant overhead
=> fix(ProcessRequest): Sanitize string inputs to remove whitespace

src/Views/Shared/HtmlElements/Link/Link.cshtml, src/Views/Shared/Link.cshtml
Issue was the forms that were changed yesterday, see commit SHA e6d07911239bd7e4b9fdd448217a6ed50ebb7ee8 on form-builder-json, of which had the "right chevron"... were not displaying the right chevron. It was loading a duplicate ( higher level ) view.
Removed duplicate Link.cshtml view from Shared folder, as it already exists in Shared/HtmlElements/Link and has ViewLocation set in AddRazorViewEngineViewLocations in ServiceCollectionExtensions.cs
Tidied the original Link.cshtml view
=> fix(duplicate_link): rm duplicate Link.cshtml

src/Views/Shared/HtmlElements/Link/Link.cshtml
Add container div to link view, ensures that buttons containing links don't appear side by side e.g. on success pages
=> chore(views): add container div to links

src/Extensions/DictionaryExtensions.cs, tests/unit-tests/UnitTests/Extensions/DictionaryExtensionsTests.cs
Fix for the previous code, which encoded all input values;
-) Now it will loop through the string[] of input values
-) Check if null
-) Check if the string contains a < or > and replace it with the encoded string equivalent
This is part of larger conversation [JIRA Card](https://stockportbi.atlassian.net/browse/DIGITAL-6501), which will be reviewing security within Form Builder, and possibly all projects.
Jon H has agreed that the card should be resolved by targeting only the two angle brackets, opening & closing.
=> fix(script_injection): change to encode only "<>"

src/Services/MappingService/MappingService.cs, tests/unit-tests/UnitTests/Services/MappingServiceTests.cs
Issue : Mapping Service > GetFormAnswers would apply "transform" to pages further down the form... 
-) Changed the foreach loop from each page on the form, to a classic for loop to transform each page up to and including the current page, based on the index taken from the page given by the page helper method.
=> fix(MappingService): foreach visited page slug

src/Models/Elements/Address.cs, tests/unit-tests/UnitTests/Models/Elements/AddressTests.cs
In response to a Kibana log probably caused by a bot trying to go direct to an address/automatic page, added a Throw to log a better error message
=> refactor(Address): add ThrowError when results is null on automatic

src/Controllers/Payment/PaymentController.cs
[Jira Issue #7655](https://stockportbi.atlassian.net/browse/DIGITAL-7655)
The Form Name that was previously in the Failure and Declined Payments views, was being populated from the form-slug. Switched it to actually use the Form Name from the BaseForm property. This renders a more user friendly form name, within the link back to the form.
=> fix(Payment): Form Name from BaseForm not slug

src/Models/Elements/Element.cs, src/Views/Shared/Booking/Booking.cshtml, src/Views/Shared/DateInput/DateInput.cshtml, src/Views/Shared/DatePicker/DatePicker.cshtml, src/Views/Shared/FileUpload/FileUpload.cshtml, src/Views/Shared/HtmlElements/Inputs/Checkbox/Checkbox.cshtml, src/Views/Shared/HtmlElements/Inputs/Radio/Radio.cshtml, src/Views/Shared/HtmlElements/Select/Select.cshtml, src/Views/Shared/HtmlElements/Textarea/Textarea.cshtml, src/Views/Shared/HtmlElements/Textbox/Textbox.cshtml, src/Views/Shared/IAG/WarningText.cshtml, src/Views/Shared/TimeInput/TimeInput.cshtml, tests/unit-tests/UnitTests/Models/ElementTests.cs
The warning element was no longer showing due to a new view we'd made for the warning property. This new view has now be renamed to 'WarningText.cshtml' in order to distinguish it, and the warning element is now displaying as it was.
A change to the WarningText div so it now has an ID in it and a matching aria-describedby tag. This was to remove the error it was getting in siteimprove.
=> fix(warning): warning element not displaying, aria described by

src/Helpers/ElementHelpers/ElementHelper.cs, src/Services/MappingService/MappingService.cs, tests/unit-tests/UnitTests/Helpers/ElementHelperTests.cs
Fix for the issue that causes forms with an AddAnother element to throw an exception if the AddAnother element has been skipped entirely.
- Add functionality inside 'GetNumberOfFieldSets' that will return 0 instead of throw an error in the case that the AddAnother element doesn't exist within FormData.
- Add early exit condition inside 'CreateAndCheckAddAnother' if element doesn't exsist within FormData.
- Clean up existing test.
=> Fix: Add Check to see if FormData is null before processing the AddAnother elements on Summary and Submission

src/Helpers/PageHelpers/IPageHelper.cs, src/Helpers/PageHelpers/PageHelper.cs, src/Services/AddAnotherService/AddAnotherService.cs, tests/unit-tests/UnitTests/Helpers/PageHelperTests.cs, tests/unit-tests/UnitTests/Services/AddAnotherServiceTests.cs
* add PageHelper method to remove FormData
* amend logic to do the optional and empty check inside the if
* instead of setting the FormData to 0, it now gets removed if all elements are optional and empty
* update unit tests
=> fix(AddAnother): fix broken AddAnother, change FormData to be removed when all optional fields empty

src/Validators/ManualAddressValidator.cs
Added a small tweak to allow the ValidaatePostcode glad, which potentially allows overseas postal/zip codes to work with manual address validation
=> Manual address override

src/Services/RetrieveExternalDataService/RetrieveExternalDataService.cs
We were hitting errors on using Retrieve External Data on the first page as a Get action type... as there were no pages available to add these answers to.
It shouldn't brake any existing forms as it's just checking if something exists before acting on it, which would throw an error if it didn't exist. Safe enough and helps us out with the way we need to use Retrieve External Data.
=> feat(ExternalData): add condition for Pages.Any()

src/TagParsers/FormAnswerTagParser.cs, src/TagParsers/FormDataTagParser.cs, tests/unit-tests/UnitTests/TagParsers/FormAnswerTagParserTests.cs, tests/unit-tests/UnitTests/TagParsers/FormDataTagParserTests.cs
Add the ability to use FormAnswer and FormData TagParsers in Element Hints
=> feat(TagParser): add Hint to FormAnswer and FormData TagParsers

src/Providers/PaymentProvider/CivicaPayProvider.cs, src/form-builder.csproj, tests/unit-tests/UnitTests/Providers/PaymentProvider/CivicaPayProviderTests.cs, tests/unit-tests/form-builder-tests-unit.csproj
Update Gateways to a pre-release to test in "int", with the Civica Pay Response corrected to be a bool property and not a string.
=> fix(CivicaPayResponse): changes string to bool

src/Services/BookingService/BookingService.cs, tests/unit-tests/UnitTests/Services/BookingServiceTests.cs
Add Limit Date to the Booking cache keys for if the user goes back and changes their answer
Update unit tests
=> fix(Booking): add Limit Date to cache keys

src/Workflows/PaymentWorkflow/PaymentWorkflow.cs, tests/unit-tests/UnitTests/Workflows/PaymentWorkflowtests.cs
Forms with payments but no CRM Case (ie we generate a reference) weren't having a reference generated. Added in a call to PreProcessSubmission to enable the reference generation
=> fix(PaymentWorkflow): add PreProcessSubmission to PaymentWorkflow

src/Providers/DocumentCreation/Generic/TextfileDocumentCreator.cs
The PDFs created by the SubmitAndEmail in form builder has text overflowing from the page. This should add a word wrap to stop that from happening.
=> chore(document-creator): add xtext formatter to pdf content

src/Providers/DocumentCreation/Generic/TextfileDocumentCreator.cs
The title of the pdf was getting an error on submission so this is just giving it the same formatting as the rest of the PDF.
=> chore(documentcreation): fix format error on pdf title

src/Helpers/EmailHelpers/EmailHelper.cs, src/Services/DocumentService/DocumentSummaryService.cs, src/Services/EmailSubmitService/EmailSubmitService.cs, tests/unit-tests/UnitTests/Services/DocumentSummaryServiceTests.cs
EmailSubmitService - remove the .Map as it's already been done once in the Worlfow
EmailHelper - remove the _sessionHelper and _mappingService + related calls as they weren't used or needed
DocumentSummaryService - remove the Transform on the ReducedPages as the Transform has already been done in the Workflow and it was causing duplication of AddAnother elements
Update unit tests accordingly
=> fix(SubmitAndEmail): remove duplicate mapping and transforms

src/Builders/SummaryAnswerBuilder.cs, tests/unit-tests/UnitTests/Helpers/DocumentCreationHelperTests.cs
Made minor changes to how the html for the email body is formed. We now wrap the question in a bold tag and we drop down to a new line for the answer.
In terms of the PDF we simply removed the colon and left as is as it was already what the email body needed to be.
=> chore(summaryanswerbuilder): making bold and on new line. fixing tests

src/Builders/ElementBuilder.cs, src/Models/Properties/ElementProperties/DateProperty.cs, src/Utils/Startup/ServiceCollectionExtensions.cs, src/Validators/DateInputIsPastDateAfterRelativeValidator.cs, src/Validators/IntegrityChecks/Elements/DateValidationsCheck.cs, tests/unit-tests/UnitTests/Validators/DateInputIsPastDateAfterRelativeValidator.cs, tests/unit-tests/UnitTests/Validators/IntegrityChecks/DateValidationsCheckTests.cs
The last of the date relative checks. This one ensures that the date is inside the past range,
e.g.    bbbbbbggggg[todaysDate]bbbbbbbbbb
=> chore(ispastdateafterrelative): new validation etc

src/Validators/MaxLengthvalidator.cs, tests/unit-tests/UnitTests/Validators/MaxLengthValidatorTests.cs
made a generic validation message appear when too many characters entered into a text area
=> fix(maxlengthvalidation): using generic message on over error messages

src/Services/BookingService/BookingService.cs, tests/unit-tests/UnitTests/Services/BookingServiceTests.cs
As the new Bookings API has admin override options for the internal UI, we now need an extra filter on the availability response before the calendar renders : previously the call only returned dates with availability, now it returns all dates with a bool of available or not
=> refactor(BookingService): add filter on HasAvailableAppointments

src/Extensions/FormAnswersExtensions.cs, src/Utils/Startup/ServiceCollectionExtensions.cs, src/form-builder.csproj, tests/unit-tests/form-builder-tests-unit.csproj
=> chore(Gateways): update package, increase cache timout

src/Controllers/Document/DocumentController.cs, src/Workflows/DocumentWorkflow/DocumentWorkflow.cs, src/Workflows/DocumentWorkflow/IDocumentWorkflow.cs, tests/unit-tests/UnitTests/Controllers/DocumentControllerTests.cs
Change the doc creation service to use the string being used in the cache storage from the GUID it used to use.
=> Document summary issue
